### PR TITLE
Update to Kotlin 1.6.0.

### PR DESCRIPTION
**Pull request by cmelchior**
Update to Kotlin 1.6.0 + update a few other dependencies.

### CODE REVIEW

**Comment by cmelchior** [comment]
So far I'm having the following issues:
* On host13: `
Exception in thread "main" java.lang.IllegalStateException: Unsupported Xcode version 12.4, minimal supported version is 12.5.`
* Variant selection seems to be broken for compiler tests. Unsure why this is suddenly a problem:

```
* What went wrong:
Could not determine the dependencies of task ':plugin-compiler:test'.
> Could not resolve all task dependencies for configuration ':plugin-compiler:testRuntimeClasspath'.
   > Could not resolve project :library-base.
     Required by:
         project :plugin-compiler
      > The consumer was configured to find a runtime of a library compatible with Java 8, packaged as a jar, preferably optimized for standard JVMs, and its dependencies declared externally, as well as attribute 'org.jetbrains.kotlin.platform.type' with value 'jvm'. However we cannot choose between the following variants of project :library-base:
          - jvmRuntimeElements
          - ktlint
        All of them match the consumer attributes:
          - Variant 'jvmRuntimeElements' capability io.realm.kotlin:library-base:0.8.0-SNAPSHOT declares a runtime of a library, packaged as a jar, preferably optimized for standard JVMs, as well as attribute 'org.jetbrains.kotlin.platform.type' with value 'jvm':
              - Unmatched attributes:
                  - Doesn't say anything about how its dependencies are found (required its dependencies declared externally)
                  - Doesn't say anything about its target Java version (required compatibility with Java 8)

```

**Comment by cmelchior** [comment]
Still need to investigate potential XCode issues one one of our builders. But otherwise this should be ready for review.

I had to refactor our Ktlint support as the gradle plugin for controlling apparently had issues when combined with Kotlin 1.6.0. Not 100% sure what it was about, but removing it was relatively easy.

**Review by rorbech — COMMENTED** [review]
LGTM for now

**Comment by cmelchior** [comment]
XCode has been upgraded on host_13. So this should now be fully ready for review.

**Review by rorbech — APPROVED** [review]

**Pull request merged**
