### PR TITLE
Add support for SyncConfiguration.with

### PR DESCRIPTION
**Pull request by cmelchior**
Closes https://github.com/realm/realm-kotlin/issues/504
Blocked by #795 

- Add support for Integer and Null partition values.
- Temporarily remove the partition value from the public API since it exposes internal details we want to hide.
- Add support for shorthand `SyncConfiguration.with()` similar to how `RealmConfiguration.with()` works.

### CODE REVIEW

**Comment by cmelchior** [comment]
I'm trying to hunt down some flaky tests that this PR seems to expose, but the reset of the PR should be ready for review.

**Review by rorbech — COMMENTED** [review]
We could also just have made a public `PartitionValue` with factory methods `of(...)` for the various types ... then we wouldn't have to add all these specific constructor/`with`-variants.

But LGTM ... but I will await approving until I see how many tests you'll have to ignore 🤣

**Review by edualonso — APPROVED** [review]
It looks good to me 👍

**Comment by cmelchior** [comment]
Exposing a public `PartitionValue` just seems to add another level of indirection, ie. a PartitionValue would then need to have 3 similar constructors, so we would need to document them there instead.

Also it would make all callsites like this `SyncConfiguration.with(user, PartititionValue("my-partition"), setOf())` which also feels slightly annoying.

We agreed to just ship hiding it for now, and can then re-evaluate. We can easily add a wrapper later without breaking the API.

**Pull request merged**
